### ISSUE TITLE
How to specify Coveralls endpoint?

### ISSUE THREAD

**Issue by muttleyxd** [lizheming/drone-coveralls#1]
Is there an option to specify Coveralls endpoint?
It would be useful, since I'm using self-hosted alternative which is compatible with Coveralls.

**Comment by lizheming** [comment]
We used [node-coveralls](https://github.com/nickmerwin/node-coveralls/blob/master/lib/sendToCoveralls.js#L5) before, and it written entrypoint in the code we can't config it. 
I  find [goveralls](https://github.com/mattn/goveralls) support it, we'll change to it as soon as possible. please wait a second.

**Comment by lizheming** [comment]
Oops, I misunderstand [node-coveralls](https://github.com/nickmerwin/node-coveralls/blob/a96ab2674f4ea53978f45e432d9c691a57673934/lib/sendToCoveralls.js#L6-L8), It has been supported endpoint configure. Just set environment variable `COVERALLS_ENDPOINT` with your self hosted address.

```yml
- name: coveralls
  image: lizheming/drone-coveralls
  environment:
    COVERALLS_ENDPOINT: http://self-hosted.coveralls.io
    COVERALLS_REPO_TOKEN:
      from_secret: coveralls_token
```
