### ISSUE TITLE
coveralls.js no such file or directory

### ISSUE THREAD

**Issue by ashleysommer** [lizheming/drone-coveralls#4]
```
-- Pushing coverage to Coveralls.io...
-- Sending ./.coverage to Coveralls.io --
/usr/src/app/entrypoint.sh: line 24: ./node_modules/coveralls/bin/coveralls.js: No such file or directory
```

my drone step:
```
- name: coveralls
  image: lizheming/drone-coveralls
  environment:
    COVERALLS_REPO_TOKEN:
      from_secret: coveralls_token
  settings:
    files:
    - ./.coverage
```

**Comment by ashleysommer** [comment]
I've found the problem.
Drone starts the container in: `/drone/src`
But this container assumes the working directory at startup is `/usr/src/app` (where node_modules lives).

**Comment by ashleysommer** [comment]
This is my new drone step that seems to be working:
```
- name: coveralls
  image: lizheming/drone-coveralls
  environment:
    COVERALLS_SERVICE_NAME: MyRepoName
    COVERALLS_REPO_TOKEN:
      from_secret: coveralls_token
  settings:
    files:
    - /drone/src/.coverage
  commands:
  - export COVERALLS_SERVICE_NUMBER="$DRONE_BUILD_NUMBER"
  - export COVERALLS_SERVICE_JOB_ID="$DRONE_STAGE_NAME"
  - export COVERALLS_SERVICE_JOB_NUMBER="$DRONE_STAGE_NUMBER"
  - export COVERALLS_FLAG_NAME="$DRONE_STAGE_KIND"
  - export COVERALLS_GIT_REPO="$DRONE_REPO_NAME"
  - export COVERALLS_GIT_BRANCH="$DRONE_SOURCE_BRANCH"
  - cd /usr/src/app && /usr/src/app/entrypoint.sh
```
